---
engines:
  eslint:
    enabled: true
    checks:
      no-unused-expressions:
        enabled: false
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
ratings:
  paths:
  - "**.js"
exclude_paths: 
